// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Cargar explícitamente las variables de entorno
config({ path: '.env' });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node -r tsconfig-paths/register prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
