import { prisma } from "@/configs";
import type { Prisma, PrismaClient } from "@prisma/client";
import { ConsultationStatus } from "@prisma/client";
import { CreateInvoiceDto, CreateInvoiceDetailDto, UpdateInvoiceDto } from "./invoice.interface";
import { Decimal } from "@prisma/client/runtime/client";
import { resolveExchangeRate } from "@/utils/exchange-rate.util";

type DbClient = PrismaClient | Prisma.TransactionClient;

const invoiceSelect = {
    id: true,
    patientId: true,
    receptionistId: true,
    exchangeRateId: true,
    total_usd: true,
    statusId: true,
    taxId: true,
    status: {
        select: { id: true, name: true, color_hex: true },
    },
    exchangeRate: {
        select: { id: true, rate: true, createdAt: true, is_active: true },
    },
    tax: {
        select: { id: true, name: true, rate: true, code: true, isActive: true },
    },
    patient: {
        select: {
            id: true,
            ci: true,
            name: true,
            user: { select: { id: true, ci: true, name: true } },
        },
    },
    receptionist: {
        select: {
            id: true,
            ci: true,
            name: true,
        },
    },
    payments: {
        select: {
            id: true,
            paymentMethodId: true,
            amount_paid: true,
            igtf_amount: true,
            exchangeRateId: true,
            paymentMethod: {
                select: { id: true, name: true, type: true, currency: true, is_active: true },
            },
            exchangeRate: {
                select: { id: true, rate: true, createdAt: true, is_active: true },
            },
        },
    },
} as const;

function roundMoney(value: number) {
    return Math.round((value + Number.EPSILON) * 100) / 100;
}

function computeTotals(details: Array<{ quantity: number; unit_price: any }>) {
    const totalUsd = details.reduce((acc, d) => acc + Number(d.quantity) * Number(d.unit_price), 0);
    return roundMoney(totalUsd);
}

function computeCommissions(details: Array<{ quantity: number; unit_price: any; is_commissionable: boolean }>, clinicPercent: number) {
    const commissionableTotal = details
        .filter((d) => d.is_commissionable)
        .reduce((acc, d) => acc + Number(d.quantity) * Number(d.unit_price), 0);

    const clinicAmount = (commissionableTotal * clinicPercent) / 100;
    const doctorAmount = commissionableTotal - clinicAmount;

    return {
        clinic_percent: clinicPercent,
        doctor_percent: 100 - clinicPercent,
        base_commissionable_usd: roundMoney(commissionableTotal),
        clinic_amount_usd: roundMoney(clinicAmount),
        doctor_amount_usd: roundMoney(doctorAmount),
    };
}

export class InvoiceService {

    constructor(private db: DbClient = prisma) { }

    private async resolveStatusId(statusId?: number, tx?: Prisma.TransactionClient) {
        if (statusId) {
            const status = await (tx || this.db).statusInvoice.findUnique({ where: { id: statusId } });
            if (!status) throw new Error("El status de la factura no existe");
            return status;
        }

        const proforma = await (tx || this.db).statusInvoice.findFirst({ where: { name: { equals: "Proforma", mode: "insensitive" } } });
        if (proforma) return proforma;

        const any = await (tx || this.db).statusInvoice.findFirst({ orderBy: { id: "asc" } });
        if (!any) throw new Error("No existe ningún status de factura (cree uno primero)");
        return any;
    }

    private async resolveDefaultTaxId(tx?: Prisma.TransactionClient) {
        const tax = await (tx || this.db).tax.findFirst({ where: { isActive: true }, orderBy: { id: "asc" } });
        if (!tax) throw new Error("No existe ningún impuesto activo (cree al menos uno)");
        return tax.id;
    }

    private async autoGenerateDetails(consultationId: number): Promise<CreateInvoiceDetailDto[]> {
        const consultation = await this.db.consultation.findUnique({
            where: { id: consultationId },
            select: {
                id: true,
                doctor: {
                    select: {
                        specialty: {
                            select: {
                                name: true,
                                consultation_price: true,
                            },
                        },
                    },
                },
                supplies: {
                    select: {
                        quantity: true,
                        supply: {
                            select: {
                                id: true,
                                name: true,
                                cost_price: true,
                            },
                        },
                    },
                },
            },
        });

        if (!consultation) throw new Error("La consulta no existe");

        const taxId = await this.resolveDefaultTaxId();

        const details: CreateInvoiceDetailDto[] = [];

        details.push({
            description: `Consulta - ${consultation.doctor.specialty.name}`,
            quantity: 1,
            unit_price: Number(consultation.doctor.specialty.consultation_price),
            taxId,
            is_commissionable: true,
        });

        for (const supply of consultation.supplies) {
            const supplyQty = Number(supply.quantity);
            const unitPrice = Number(supply.supply.cost_price) * supplyQty;

            details.push({
                productId: supply.supply.id,
                description: `Insumo - ${supply.supply.name} (x${supplyQty})`,
                quantity: 1,
                unit_price: unitPrice,
                taxId,
                is_commissionable: false,
            });
        }

        return details;
    }

    private async createImpl(data: CreateInvoiceDto) {
        const exchangeRate = await resolveExchangeRate(data.exchangeRateId, this.db);
        const status = await this.resolveStatusId(data.statusId);

        // const details = data.details && data.details.length > 0
        //     ? data.details
        //     : await this.autoGenerateDetails(1);

        // const totalUsd = computeTotals(details);
        // const totalBs = roundMoney(totalUsd * Number(exchangeRate.rate));

        const taxId = data.taxId ?? (await this.resolveDefaultTaxId());

        const created = await this.db.invoice.create({
            data: {
                patientId: data.patientId,
                receptionistId: data.receptionistId,
                exchangeRateId: exchangeRate.id,
                statusId: status.id,
                taxId,

                total_usd: data.total_usd ? Number(data.total_usd) : 0,
            },
            select: invoiceSelect,
        });

        // const clinicPercent = Number(created.consultation.doctor.specialty.commission_percentage);
        // const commissions = computeCommissions(
        //     created.details.map((d) => ({
        //         quantity: d.quantity,
        //         unit_price: d.unit_price,
        //         is_commissionable: d.is_commissionable,
        //     })),
        //     clinicPercent,
        // );

        return { created, commissions: null };
    }

    async createStrict(data: CreateInvoiceDto) {
        const { created, commissions } = await this.createImpl(data);
        return { ...created, commissions };
    }

    async create(data: CreateInvoiceDto) {
        try {
            const { created, commissions } = await prisma.$transaction(async (tx) => {
                const exchangeRate = await resolveExchangeRate(data.exchangeRateId, tx);
                const status = await this.resolveStatusId(data.statusId, tx);

                const taxId = data.taxId ?? (await this.resolveDefaultTaxId(tx));

                if (data.payments.length === 0) {
                    throw new Error("Debe haber al menos un pago");
                }

                let totalPaymentUsd = 0;
                for (const payment of data.payments) {
                    const method = await tx.paymentMethod.findUnique({ where: { id: payment.paymentMethodId } });
                    if (!method) throw new Error(`El método de pago con ID ${payment.paymentMethodId} no existe`);
                    
                    if (method.currency !== "USD") {
                        totalPaymentUsd += Number(payment.amount_paid) * Number(exchangeRate.rate);
                    } // esto es temporal, luego se permitirá en otras monedas
                    totalPaymentUsd += payment.amount_paid;
                }

                let totalUsd: number | null = null;
                let computedCommissions: ReturnType<typeof computeCommissions> | null = null;

                if (data.appointmentId) {
                    const appointment = await tx.appointment.findUnique({
                        where: { id: data.appointmentId },
                        select: { doctorId: true, patientId: true },
                    });
                    if (!appointment) throw new Error("La cita no existe");
                    if (appointment.patientId !== data.patientId) throw new Error("La cita no pertenece al paciente");

                    const doctor = await tx.doctor.findUnique({
                        where: { id: appointment.doctorId },
                        select: { specialtyId: true },
                    });
                    if (!doctor) throw new Error("El doctor de la cita no existe");

                    const specialty = await tx.medicalSpecialty.findUnique({
                        where: { id: doctor.specialtyId },
                        select: { consultation_price: true, commission_percentage: true },
                    });
                    if (!specialty) throw new Error("La especialidad del doctor no existe");

                    totalUsd = Number(specialty.consultation_price);

                    const clinicPercent = Number(specialty.commission_percentage);
                    if (!Number.isNaN(clinicPercent)) {
                        computedCommissions = computeCommissions(
                            [{ quantity: 1, unit_price: totalUsd, is_commissionable: true }],
                            clinicPercent,
                        );
                    }
                } else {
                    if (data.total_usd === undefined || data.total_usd === null) {
                        throw new Error("Debe indicar total_usd o appointmentId");
                    }
                    totalUsd = Number(data.total_usd);
                }

                if (totalUsd === null || Number.isNaN(totalUsd)) {
                    throw new Error("total_usd inválido");
                }

                if (totalPaymentUsd < totalUsd) {
                    return {
                        status: 400,
                        message: `El total pagado en USD (${totalPaymentUsd.toFixed(2)}) es menor al total de la factura (${totalUsd.toFixed(2)})`,
                        data: null,
                    };  
                }

                const created = await tx.invoice.create({
                    data: {
                        patientId: data.patientId,
                        receptionistId: data.receptionistId,
                        exchangeRateId: exchangeRate.id,
                        statusId: status.id,
                        taxId,

                        total_usd: totalUsd,
                    },
                    select: invoiceSelect,
                });

                for (const payment of data.payments) {
                    await tx.invoicePayment.create({
                        data: {
                            invoiceId: created.id,
                            paymentMethodId: payment.paymentMethodId,
                            amount_paid: payment.amount_paid,
                            igtf_amount: payment.igtf_amount,
                            exchangeRateId: exchangeRate.id,
                        },
                    });
                }

                if (data.appointmentId) {
                    const appointment = await tx.appointment.findUnique({
                        where: { id: data.appointmentId },
                        select: { doctorId: true, date_time: true },
                    });

                    if (!appointment) {
                        throw new Error("La cita no existe");
                    }

                    await tx.consultation.create({
                        data: {
                            invoiceId: created.id,
                            doctorId: appointment.doctorId,
                            date: appointment.date_time,
                            status: ConsultationStatus.PENDING,
                        },
                    });
                }

                return { created, commissions: computedCommissions };
            });

            return {
                status: 201,
                message: "Factura creada éxitosamente",
                data: { ...created, commissions },
            };
        } catch (error) {
            console.error("Error creando la factura:", error);

            return {
                status: 500,
                message: "Error interno al crear la factura",
                error: error instanceof Error ? error.message : "Error desconocido",
            };
        }
    }

    async findAll() {
        try {
            const invoices = await this.db.invoice.findMany({
                orderBy: { id: "desc" },
                select: invoiceSelect,
            });

            const invoicesProcessed = invoices.map((invoice) => {
                const exchangeRate = invoice.exchangeRate.rate;
                
                let totalBs = new Decimal(Number(invoice.total_usd));
                 
                totalBs = totalBs.mul(new Decimal(exchangeRate));


                return { ...invoice, total_bs: totalBs.toNumber() };
                
            });

            return {
                status: 200,
                message: invoices.length === 0 ? "No se encontraron facturas" : "Facturas encontradas éxitosamente",
                data: invoicesProcessed,
            };
        } catch (error) {
            console.error("Error buscando facturas:", error);

            return {
                status: 500,
                message: "Error interno al buscar facturas",
                error: error instanceof Error ? error.message : "Error desconocido",
            };
        }
    }

    async findByPatientId(patientId: number) {
        try {
            const invoices = await this.db.invoice.findMany({
                where: { patientId },
                orderBy: { id: "desc" },
                select: invoiceSelect,
            });

            const invoicesProcessed = invoices.map((invoice) => {
                const exchangeRate = invoice.exchangeRate.rate;
                
                let totalBs = new Decimal(Number(invoice.total_usd));
                 
                totalBs = totalBs.mul(new Decimal(exchangeRate));


                return { ...invoice, total_bs: totalBs.toNumber() };
                
            });

            return {
                status: 200,
                message: invoices.length === 0 ? "No se encontraron facturas para el paciente" : "Facturas encontradas éxitosamente",
                data: invoicesProcessed,
            };
        } catch (error) {
            console.error("Error buscando facturas:", error);

            return {
                status: 500,
                message: "Error interno al buscar facturas",
                error: error instanceof Error ? error.message : "Error desconocido",
            };
        }
    }

    // async findOne(id: number) {
    //     try {
    //         const invoice = await this.db.invoice.findUnique({
    //             where: { id },
    //             select: invoiceSelect,
    //         });

    //         if (!invoice) {
    //             return {
    //                 status: 404,
    //                 message: "Factura no encontrada",
    //                 data: null,
    //             };
    //         }

    //         const clinicPercent = Number(invoice.consultation.doctor.specialty.commission_percentage);
    //         const commissions = computeCommissions(
    //             invoice.details.map((d) => ({
    //                 quantity: d.quantity,
    //                 unit_price: d.unit_price,
    //                 is_commissionable: d.is_commissionable,
    //             })),
    //             clinicPercent,
    //         );

    //         return {
    //             status: 200,
    //             message: "Factura encontrada éxitosamente",
    //             data: { ...invoice, commissions },
    //         };
    //     } catch (error) {
    //         console.error("Error buscando la factura:", error);

    //         return {
    //             status: 500,
    //             message: "Error interno al buscar la factura",
    //             error: error instanceof Error ? error.message : "Error desconocido",
    //         };
    //     }
    // }

    // async update(id: number, data: UpdateInvoiceDto) {
    //     try {
    //         const existing = await this.db.invoice.findUnique({ where: { id }, select: { total_usd: true } });
    //         if (!existing) {
    //             return {
    //                 status: 404,
    //                 message: "Factura no encontrada",
    //                 data: null,
    //             };
    //         }

    //         let newTotalBs: number | undefined;
    //         if (data.exchangeRateId) {
    //             const rate = await this.db.exchangeRate.findUnique({ where: { id: data.exchangeRateId } });
    //             if (!rate) throw new Error("La tasa de cambio no existe");
    //             newTotalBs = roundMoney(Number(existing.total_usd) * Number(rate.rate));
    //         }

    //         const updated = await this.db.invoice.update({
    //             where: { id },
    //             data: {
    //                 ...data,
    //                 total_bs: newTotalBs,
    //             },
    //             select: invoiceSelect,
    //         });

    //         const clinicPercent = Number(updated.consultation.doctor.specialty.commission_percentage);
    //         const commissions = computeCommissions(
    //             updated.details.map((d) => ({
    //                 quantity: d.quantity,
    //                 unit_price: d.unit_price,
    //                 is_commissionable: d.is_commissionable,
    //             })),
    //             clinicPercent,
    //         );

    //         return {
    //             status: 200,
    //             message: "Factura actualizada éxitosamente",
    //             data: { ...updated, commissions },
    //         };
    //     } catch (error) {
    //         console.error("Error actualizando la factura:", error);

    //         return {
    //             status: 500,
    //             message: "Error interno al actualizar la factura",
    //             error: error instanceof Error ? error.message : "Error desconocido",
    //         };
    //     }
    // }

    // async delete(id: number) {
    //     try {
    //         const deleted = await prisma.$transaction(async (tx) => {
    //             await tx.invoicePayment.deleteMany({ where: { invoiceId: id } });
    //             await tx.invoiceDetail.deleteMany({ where: { invoiceId: id } });

    //             return tx.invoice.delete({
    //                 where: { id },
    //                 select: invoiceSelect,
    //             });
    //         });

    //         return {
    //             status: 200,
    //             message: "Factura eliminada éxitosamente",
    //             data: deleted,
    //         };
    //     } catch (error) {
    //         console.error("Error eliminando la factura:", error);

    //         return {
    //             status: 500,
    //             message: "Error interno al eliminar la factura",
    //             error: error instanceof Error ? error.message : "Error desconocido",
    //         };
    //     }
    // }
}
